/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication54;

import javax.swing.JOptionPane;

/**
 *
 * @author ovais
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider4 = new javax.swing.JSlider();
        jSlider9 = new javax.swing.JSlider();
        jSlider11 = new javax.swing.JSlider();
        jSlider13 = new javax.swing.JSlider();
        jSlider18 = new javax.swing.JSlider();
        jSlider19 = new javax.swing.JSlider();
        jSlider20 = new javax.swing.JSlider();
        jSlider21 = new javax.swing.JSlider();
        jSlider22 = new javax.swing.JSlider();
        jSlider23 = new javax.swing.JSlider();
        jSlider24 = new javax.swing.JSlider();
        jSlider25 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea0 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.pink);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 1000));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider4.setMajorTickSpacing(20);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setSnapToTicks(true);
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 130));

        jSlider9.setMajorTickSpacing(20);
        jSlider9.setPaintLabels(true);
        jSlider9.setPaintTicks(true);
        jSlider9.setSnapToTicks(true);
        jSlider9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, 50));

        jSlider11.setMajorTickSpacing(20);
        jSlider11.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider11.setPaintLabels(true);
        jSlider11.setPaintTicks(true);
        jSlider11.setSnapToTicks(true);
        getContentPane().add(jSlider11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 60, 130));

        jSlider13.setMajorTickSpacing(20);
        jSlider13.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider13.setPaintLabels(true);
        jSlider13.setPaintTicks(true);
        jSlider13.setSnapToTicks(true);
        getContentPane().add(jSlider13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, 130));

        jSlider18.setMajorTickSpacing(20);
        jSlider18.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider18.setPaintLabels(true);
        jSlider18.setPaintTicks(true);
        jSlider18.setSnapToTicks(true);
        getContentPane().add(jSlider18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 60, 130));

        jSlider19.setMajorTickSpacing(20);
        jSlider19.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider19.setPaintLabels(true);
        jSlider19.setPaintTicks(true);
        jSlider19.setSnapToTicks(true);
        getContentPane().add(jSlider19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 60, 130));

        jSlider20.setMajorTickSpacing(20);
        jSlider20.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider20.setPaintLabels(true);
        jSlider20.setPaintTicks(true);
        jSlider20.setSnapToTicks(true);
        getContentPane().add(jSlider20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 60, 130));

        jSlider21.setMajorTickSpacing(20);
        jSlider21.setPaintLabels(true);
        jSlider21.setPaintTicks(true);
        jSlider21.setSnapToTicks(true);
        jSlider21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, 50));

        jSlider22.setMajorTickSpacing(20);
        jSlider22.setPaintLabels(true);
        jSlider22.setPaintTicks(true);
        jSlider22.setSnapToTicks(true);
        jSlider22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 150, 50));

        jSlider23.setMajorTickSpacing(20);
        jSlider23.setPaintLabels(true);
        jSlider23.setPaintTicks(true);
        jSlider23.setSnapToTicks(true);
        jSlider23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, 50));

        jSlider24.setMajorTickSpacing(20);
        jSlider24.setPaintLabels(true);
        jSlider24.setPaintTicks(true);
        jSlider24.setSnapToTicks(true);
        jSlider24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 150, 50));

        jSlider25.setMajorTickSpacing(20);
        jSlider25.setPaintLabels(true);
        jSlider25.setPaintTicks(true);
        jSlider25.setSnapToTicks(true);
        jSlider25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSlider25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, 50));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 50, 30));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 50, 30));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 50, 30));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 30));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 50, 30));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 50, 30));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea0.setEditable(false);
        jTextArea0.setColumns(20);
        jTextArea0.setRows(5);
        jScrollPane7.setViewportView(jTextArea0);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, 30));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 50, 30));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane9.setViewportView(jTextArea7);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 50, 30));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 110, 50));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 70, 30));

        jLabel1.setText("Enter your City Number (0-9)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 160, 20));

        jLabel2.setText("Adjust the slider for your distances and enter citynumber below to Calculate the shortest path to all cites");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 700, 30));

        jLabel3.setText("City 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setText("City 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel5.setText("City 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel6.setText("City 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setText("City 5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel8.setText("City 6");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, 10));

        jLabel9.setText("City 7");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel10.setText("City 8");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel11.setText("City 9");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(Integer.parseInt(jTextField1.getText())<1||Integer.parseInt(jTextField1.getText())>9){
         JOptionPane.showMessageDialog(null,
                    "Please ensure your city number is between 1-9",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
     }
     else{
        Ronaldo graph =new Ronaldo(9);
       graph.addEdge(1, 4, jSlider4.getValue());
        graph.addEdge(1, 2, jSlider21.getValue());
        graph.addEdge(2, 5, jSlider13.getValue());
        graph.addEdge(2, 3, jSlider25.getValue());
        graph.addEdge(3, 6, jSlider19.getValue());
        graph.addEdge(4, 5, jSlider9.getValue());
        graph.addEdge(4, 7, jSlider18.getValue());
        graph.addEdge(5, 6, jSlider23.getValue());
        graph.addEdge(5, 8, jSlider11.getValue());
        graph.addEdge(8, 9, jSlider24.getValue());
        graph.addEdge(7, 8, jSlider22.getValue());
        graph.addEdge(6, 9, jSlider20.getValue());
        graph.computeSortestPathsFrom((Integer.parseInt(jTextField1.getText())) );
        
            jTextArea0.setText(Integer.toString(graph.ABC[0]));
            jTextArea1.setText(Integer.toString(graph.ABC[1]));
            jTextArea2.setText(Integer.toString(graph.ABC[2]));
            jTextArea3.setText(Integer.toString(graph.ABC[3]));
            jTextArea4.setText(Integer.toString(graph.ABC[4]));
            jTextArea5.setText(Integer.toString(graph.ABC[5]));
            jTextArea6.setText(Integer.toString(graph.ABC[6]));
            jTextArea7.setText(Integer.toString(graph.ABC[7]));
            jTextArea8.setText(Integer.toString(graph.ABC[8]));
                    
        
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSlider jSlider11;
    private javax.swing.JSlider jSlider13;
    private javax.swing.JSlider jSlider18;
    private javax.swing.JSlider jSlider19;
    private javax.swing.JSlider jSlider20;
    private javax.swing.JSlider jSlider21;
    private javax.swing.JSlider jSlider22;
    private javax.swing.JSlider jSlider23;
    private javax.swing.JSlider jSlider24;
    private javax.swing.JSlider jSlider25;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider9;
    private javax.swing.JTextArea jTextArea0;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
